// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Viaproxima.Web.Data;

#nullable disable

namespace Viaproxima.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260125160159_AddCharacterStats")]
    partial class AddCharacterStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Viaproxima.Web.Data.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Akrobatik")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Allmanbildning")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aurar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Barformaga")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Blockera")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Brottas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cuppar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ferrar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fingerfardighet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Forflytta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fysisk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Genomslag")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intryck")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KannaAvFara")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Klokhet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ljuga")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogisktTankande")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MagiskKansla")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mental")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OgaForDetaljer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Overtala")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeIgenomLogner")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkadaArmar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkadaBen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkadaHuvud")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkadaTorso")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Skicklighet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Skytte")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Snabbtankthet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Talighet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Traffsakerhet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Uppfinningsrikedom")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Uthallighet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Utstralning")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VackaKanslor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Xp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Viaproxima.Web.Data.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cols")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Durability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconPrimary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconSecondary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMagic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Primary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rows")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Secondary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("Viaproxima.Web.Data.InventoryItem", b =>
                {
                    b.HasOne("Viaproxima.Web.Data.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });
#pragma warning restore 612, 618
        }
    }
}
